### ISSUE TITLE
Soap extension is needed for Magento 2.2.0.

### ISSUE THREAD

**Issue by tzyganu** [fballiano/docker-magento2-apache-php#2]
Magento 2.2 requires php-soap extension to work.  
https://github.com/magento/magento2/blob/2.2-develop/composer.json#L71  
This should be added in the Dockerfile.

**Comment by fballiano** [comment]
Hi @tzyganu, it's an honor to get a message from you :)

I added soap to the dockerfile, the image is building on https://hub.docker.com/r/fballiano/magento2-apache-php/builds/ and should be ready in a few minutes.

hope it solves the problem.
thanks!

**Comment by tzyganu** [comment]
@fballiano It's an honor to contribute to this even as little as I did. 
Your docker "suite" for magento 2 saved my mental sanity.

**Comment by fballiano** [comment]
great to hear :-)

and this comment made my day, thank man
