### ISSUE TITLE
Versions

### ISSUE THREAD

**Issue by wodka** [fballiano/docker-magento2-apache-php#4]
Hi, just had the problem that after an image pull my magento 2.2.x container stopped working -> can you add tags to your builds / versions to have them fixed to a specific magento version?

ie:
* fballiano/magento2-apache-php:2.2 (for php <= 7.1
* fballiano/magento2-apache-php:2.3 (for php > 7.1)

on dockerhub I usually set it like this:

![image](https://user-images.githubusercontent.com/385731/61712942-b90e6880-ad57-11e9-87d6-3fd5bfe4883b.png)

**Comment by hasanr68** [comment]
Hi there - same problem. Did you figure out what to do?

**Comment by wodka** [comment]
yes, I forked the repo and created the tags: https://hub.docker.com/r/wodkamichi/docker-magento2-apache-php

**Comment by hasanr68** [comment]
Cool. Vielen dank!

**Comment by fballiano** [comment]
sorry guys, everything is tagged now for magento <=2.3 and magento 2.4 ;-)
