### ISSUE TITLE
composer update error after fresh install

### ISSUE THREAD

**Issue by nenriquez** [fballiano/docker-magento2-apache-php#5]
After fresh install I'm getting the following error after run `composer install` command.

As there is no 'unzip' command installed zip files are being unpacked using the PHP zip extension.
This may cause invalid reports of corrupted archives. Besides, any UNIX permissions (e.g. executable) defined in the archives will be lost.
Installing 'unzip' may remediate them.

I can manage to solve it running 'apt-get install zip unzip'

**Comment by fballiano** [comment]
Hi, I usually don't get the error cause I use composer outside of the containers.

anyways I've added the zip unzip to the image (only for the 2.4 branch if that's ok) and the image is rebuilding on docker hub

**Comment by nenriquez** [comment]
Thanks! Your architecture is amazing. It's work really good.

**Comment by fballiano** [comment]
thank you! glad to know! :-)
